default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: hahaha123
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
development:
  <<: *default
  database: a_toy_app_development
test:
  <<: *default
  database: a_toy_app_test_development
production:
  <<: *default
  database: a_toy_app_production_development
