default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
development:
  <<: *default
  database: <%= ENV['DB_DEVELOPMENT'] %>
test:
  <<: *default
  database: <%= ENV['DB_TEST'] %>
production:
  <<: *default
  database: <%= ENV['DB_PRODUCTION'] %>
